import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    role: v.union(v.literal('client'), v.literal('model'), v.literal('admin')),
    avatar: v.string(),
    plan: v.optional(v.union(v.literal('Free'), v.literal('Pro'), v.literal('Enterprise'))),
    firebaseUid: v.string(),
  }).index('by_firebaseUid', ['firebaseUid']),

  models: defineTable({
    user_id: v.string(),
    name: v.string(),
    avatar: v.string(),
    bio: v.string(),
    gender: v.string(),
    age: v.number(),
    height: v.number(),
    location: v.string(),
    daily_rate: v.number(),
    experience_level: v.string(),
  }).index('by_user_id', ['user_id']),

  portfolio_images: defineTable({
    model_id: v.string(),
    image_url: v.string(),
    type: v.optional(v.union(v.literal('image'), v.literal('video'))),
    mux_playback_id: v.optional(v.string()),
    mux_asset_id: v.optional(v.string()),
  }).index('by_model_id', ['model_id']),

  bookings: defineTable({
    client_id: v.string(),
    client_name: v.string(),
    client_email: v.string(),
    model_id: v.string(),
    booking_date: v.string(),
    event_name: v.string(),
    event_location: v.string(),
    additional_notes: v.optional(v.string()),
    status: v.union(v.literal('Pending'), v.literal('Accepted'), v.literal('Rejected'), v.literal('Paid')),
    payment_reference: v.optional(v.string()),
    amount: v.optional(v.number()),
  }).index('by_model_id', ['model_id']).index('by_client_id', ['client_id']),

  opportunities: defineTable({
    business_id: v.string(),
    title: v.string(),
    business_name: v.string(),
    business_logo: v.optional(v.string()),
    business_description: v.string(),
    contact_info: v.string(),
    is_verified_business: v.boolean(),
    location_state: v.string(),
    location_city: v.string(),
    category: v.string(),
    gender_requirement: v.string(),
    age_requirement: v.string(),
    experience_requirement: v.string(),
    models_needed: v.number(),
    models_accepted_count: v.number(),
    models_applied_count: v.number(),
    payment_type: v.string(),
    payment_amount: v.optional(v.number()),
    event_date: v.string(),
    deadline: v.string(),
    notes: v.optional(v.string()),
    rules: v.optional(v.string()),
    venue_address: v.optional(v.string()),
    status: v.string(),
  }).index('by_business_id', ['business_id']).index('by_status', ['status']),

  applications: defineTable({
    opportunity_id: v.string(),
    model_id: v.string(),
    full_name: v.string(),
    portfolio_photos: v.array(v.string()),
    bio: v.string(),
    instagram_handle: v.string(),
    experience_level: v.string(),
    message: v.optional(v.string()),
    status: v.union(v.literal('Pending'), v.literal('Accepted'), v.literal('Rejected'), v.literal('Withdrawn')),
  }).index('by_opportunity_id', ['opportunity_id']).index('by_model_id', ['model_id']),

  business_profiles: defineTable({
    user_id: v.string(),
    brand_name: v.optional(v.string()),
    description: v.optional(v.string()),
    industry: v.optional(v.string()),
    website: v.optional(v.string()),
    social_links: v.optional(v.array(v.string())),
    address: v.optional(v.string()),
    is_verified: v.boolean(),
    founded_year: v.optional(v.number()),
    cover_image: v.optional(v.string()),
  }).index('by_user_id', ['user_id']),
});
